# Generated by Django 3.0.3 on 2020-02-07 21:04

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination_from',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('loading_from', models.CharField(choices=[('L1', 'Zalog'), ('L2', 'BTC')], max_length=2)),
                ('zip_code', models.IntegerField()),
            ],
        ),
    ]
