# Generated by Django 3.0.3 on 2020-02-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_destination_to_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone_postal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=10)),
                ('postal_code', models.IntegerField()),
            ],
        ),
    ]
