# Generated by Django 3.0.3 on 2020-02-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_zone_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('zone', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
