# Generated by Django 3.0.3 on 2020-02-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_zone_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone_price',
            name='weight',
            field=models.CharField(max_length=10),
        ),
    ]
